# TODO: update the schema

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS synthetic_requests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL,
    task_type TEXT NOT NULL,
    prompt TEXT,
    columns TEXT NOT NULL,  -- JSON stored as TEXT in SQLite
    num_rows INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id)
);
