const exampleDatasets = [
  {
    slug: 'customer-support-tickets',
    title: 'Customer support tickets',
    rows: 1000,
    prompt: 'Generate customer support tickets with issue category, sentiment, and resolution.',
    methodology: 'Generated from a text task prompt with category, sentiment, and resolution columns, then reviewed for label variety.',
    data: [
      { ticket_text: 'The billing page charged my card twice after I upgraded.', issue_category: 'billing', sentiment: 'frustrated', resolution: 'Refund duplicate charge and confirm plan upgrade.' },
      { ticket_text: 'I cannot reset my password because the email never arrives.', issue_category: 'account_access', sentiment: 'negative', resolution: 'Verify email address and resend password reset link.' },
      { ticket_text: 'The dashboard export button is missing from my workspace.', issue_category: 'product_bug', sentiment: 'neutral', resolution: 'Enable exports for the workspace role.' },
      { ticket_text: 'Can I add three more teammates to the trial?', issue_category: 'account_management', sentiment: 'positive', resolution: 'Increase trial seat limit and send invite steps.' },
      { ticket_text: 'The generated report timed out twice this morning.', issue_category: 'performance', sentiment: 'negative', resolution: 'Restart report job and escalate timeout logs.' },
      { ticket_text: 'I need invoices for March and April for accounting.', issue_category: 'billing', sentiment: 'neutral', resolution: 'Send invoice PDFs and update billing contact.' },
      { ticket_text: 'The app says my API token is invalid after rotation.', issue_category: 'api_access', sentiment: 'frustrated', resolution: 'Confirm token scope and regenerate API credentials.' },
      { ticket_text: 'Our team wants SSO enabled before launch.', issue_category: 'security', sentiment: 'positive', resolution: 'Schedule SSO setup and provide metadata URL.' },
      { ticket_text: 'Images are uploading but not appearing in the review queue.', issue_category: 'product_bug', sentiment: 'negative', resolution: 'Reprocess uploads and check queue worker status.' },
      { ticket_text: 'How do I downgrade from Pro to Starter?', issue_category: 'billing', sentiment: 'neutral', resolution: 'Explain downgrade timing and update subscription.' },
    ],
  },
  {
    slug: 'medical-intake-forms',
    title: 'Medical intake forms',
    rows: 500,
    prompt: 'Generate de-identified medical intake records with symptoms, diagnosis codes, and triage priority.',
    methodology: 'Synthetic examples use fictional symptoms and ICD-style codes for workflow testing only; they are not medical advice.',
    data: [
      { symptoms: 'dry cough, mild fever, fatigue', diagnosis_code: 'J06.9', triage_priority: 'routine' },
      { symptoms: 'chest tightness, shortness of breath', diagnosis_code: 'R06.02', triage_priority: 'urgent' },
      { symptoms: 'ankle swelling after fall', diagnosis_code: 'S93.4', triage_priority: 'routine' },
      { symptoms: 'severe headache, blurred vision', diagnosis_code: 'R51.9', triage_priority: 'urgent' },
      { symptoms: 'abdominal cramps, nausea', diagnosis_code: 'R10.9', triage_priority: 'routine' },
      { symptoms: 'rash, itching after new medication', diagnosis_code: 'L27.0', triage_priority: 'urgent' },
      { symptoms: 'sore throat, swollen glands', diagnosis_code: 'J02.9', triage_priority: 'routine' },
      { symptoms: 'dizziness, fainting episode', diagnosis_code: 'R55', triage_priority: 'urgent' },
      { symptoms: 'lower back pain after lifting', diagnosis_code: 'M54.5', triage_priority: 'routine' },
      { symptoms: 'burning urination, pelvic discomfort', diagnosis_code: 'N39.0', triage_priority: 'routine' },
    ],
  },
  {
    slug: 'contract-clauses',
    title: 'Contract clauses',
    rows: 500,
    prompt: 'Generate contract clause snippets with clause type, risk level, and extracted entities.',
    methodology: 'Generated as synthetic legal-text snippets for extraction and classification tests; no real contracts are used.',
    data: [
      { clause_text: 'Either party may terminate this agreement with 30 days written notice.', clause_type: 'termination', risk_level: 'low', entities: 'notice_period:30 days' },
      { clause_text: 'Vendor shall indemnify Customer against all third-party IP claims.', clause_type: 'indemnity', risk_level: 'medium', entities: 'party:Vendor; party:Customer' },
      { clause_text: 'Payment is due within 15 days of invoice receipt.', clause_type: 'payment_terms', risk_level: 'low', entities: 'payment_window:15 days' },
      { clause_text: 'Customer data may be transferred to subprocessors outside the United States.', clause_type: 'data_transfer', risk_level: 'high', entities: 'region:outside United States' },
      { clause_text: 'Liability is capped at fees paid during the prior twelve months.', clause_type: 'limitation_of_liability', risk_level: 'medium', entities: 'cap:12 months fees' },
      { clause_text: 'The service level credit is the sole remedy for downtime.', clause_type: 'sla', risk_level: 'medium', entities: 'remedy:service credit' },
      { clause_text: 'Confidential information excludes data independently developed by the recipient.', clause_type: 'confidentiality', risk_level: 'low', entities: 'exclusion:independent development' },
      { clause_text: 'Provider may suspend access immediately for suspected misuse.', clause_type: 'suspension', risk_level: 'high', entities: 'trigger:suspected misuse' },
      { clause_text: 'This agreement is governed by the laws of Delaware.', clause_type: 'governing_law', risk_level: 'low', entities: 'jurisdiction:Delaware' },
      { clause_text: 'Renewal occurs automatically unless cancelled 60 days before the term end.', clause_type: 'renewal', risk_level: 'medium', entities: 'notice_period:60 days' },
    ],
  },
  {
    slug: 'product-reviews',
    title: 'Product reviews',
    rows: 1000,
    prompt: 'Generate product reviews with star rating, sentiment, and product category.',
    methodology: 'Generated as balanced review text across ratings, sentiment labels, and ecommerce categories.',
    data: [
      { review_text: 'Battery lasts all day and the screen is bright outdoors.', star_rating: 5, sentiment: 'positive', product_category: 'electronics' },
      { review_text: 'The fabric feels cheap and the seams started fraying quickly.', star_rating: 2, sentiment: 'negative', product_category: 'apparel' },
      { review_text: 'Easy to assemble, though one screw was missing.', star_rating: 3, sentiment: 'mixed', product_category: 'furniture' },
      { review_text: 'Smells great and does not irritate my skin.', star_rating: 5, sentiment: 'positive', product_category: 'beauty' },
      { review_text: 'The handle cracked after two uses.', star_rating: 1, sentiment: 'negative', product_category: 'kitchen' },
      { review_text: 'Good value for the price, but shipping was slow.', star_rating: 4, sentiment: 'mixed', product_category: 'home' },
      { review_text: 'My dog loves it and the stitching is durable.', star_rating: 5, sentiment: 'positive', product_category: 'pet_supplies' },
      { review_text: 'The sizing chart was inaccurate.', star_rating: 2, sentiment: 'negative', product_category: 'apparel' },
      { review_text: 'Works exactly as described and paired quickly.', star_rating: 4, sentiment: 'positive', product_category: 'electronics' },
      { review_text: 'Flavor was fine, but the package arrived dented.', star_rating: 3, sentiment: 'mixed', product_category: 'grocery' },
    ],
  },
  {
    slug: 'pii-redaction-test',
    title: 'PII redaction test dataset',
    rows: 200,
    prompt: 'Generate synthetic PII examples for testing redaction pipelines.',
    methodology: 'Uses fake names, emails, phone numbers, and IDs for redaction test cases; no real identities are included.',
    data: [
      { text: 'Contact Maya Torres at maya.torres@example.test or 415-555-0182.', pii_type: 'email,phone,name', expected_redaction: 'Contact [NAME] at [EMAIL] or [PHONE].' },
      { text: 'Employee ID E49382 belongs to Jordan Lee.', pii_type: 'employee_id,name', expected_redaction: 'Employee ID [EMPLOYEE_ID] belongs to [NAME].' },
      { text: 'Ship to 42 Linden Ave, Portland, OR 97205.', pii_type: 'address', expected_redaction: 'Ship to [ADDRESS].' },
      { text: 'SSN 078-05-1120 was entered in the test form.', pii_type: 'ssn', expected_redaction: 'SSN [SSN] was entered in the test form.' },
      { text: 'Passport X94827133 expires next June.', pii_type: 'passport', expected_redaction: 'Passport [PASSPORT] expires next June.' },
      { text: 'Call Priya Nair at 212-555-0199 for confirmation.', pii_type: 'name,phone', expected_redaction: 'Call [NAME] at [PHONE] for confirmation.' },
      { text: 'The account recovery email is devon.park@example.test.', pii_type: 'email', expected_redaction: 'The account recovery email is [EMAIL].' },
      { text: 'Card 4111 1111 1111 1111 failed validation.', pii_type: 'credit_card', expected_redaction: 'Card [CREDIT_CARD] failed validation.' },
      { text: 'MRN MR48291 appears in the sample note.', pii_type: 'medical_record_number', expected_redaction: 'MRN [MRN] appears in the sample note.' },
      { text: 'Vehicle VIN 5YJ3E1EA7KF317000 was logged.', pii_type: 'vin', expected_redaction: 'Vehicle VIN [VIN] was logged.' },
    ],
  },
  {
    slug: 'japanese-qa',
    title: 'Japanese Q&A pairs',
    rows: 500,
    prompt: 'Generate Japanese question-answer pairs with topic labels.',
    methodology: 'Generated as short Japanese Q&A rows across travel, food, technology, and workplace topics.',
    data: [
      { question: 'Tokyo Station kara kuko e iku ichiban hayai hoho wa nan desu ka?', answer: 'Narita Express mata wa airport limousine bus ga benri desu.', topic: 'travel' },
      { question: 'Miso shiru ni au guzai wa nan desu ka?', answer: 'Tofu, wakame, negi ga teiban desu.', topic: 'food' },
      { question: 'Niyoso ninsho wa naze taisetsu desu ka?', answer: 'Password ga morete mo fusei login wo fusegi yasuku naru tame desu.', topic: 'technology' },
      { question: 'Kaigi no gijiroku ni wa nani wo kaku beki desu ka?', answer: 'Kettei jikou, tantosha, kigen wo meikaku ni kiroku shimasu.', topic: 'workplace' },
      { question: 'Kyoto de ninki no kankochi wa doko desu ka?', answer: 'Kiyomizudera, Fushimi Inari Taisha, Arashiyama nado ga ninki desu.', topic: 'travel' },
      { question: 'Matcha to wa nan desu ka?', answer: 'Ryokucha no chaba wo funmatsu ni shita nihoncha desu.', topic: 'food' },
      { question: 'Cloud hozon no riten wa nan desu ka?', answer: 'Fukusu no tanmatsu kara access dekite, backup ni mo yakudachimasu.', topic: 'technology' },
      { question: 'Joshi ni shinchoku wo hokoku suru toki no kotsu wa nan desu ka?', answer: 'Genzai no jokyo, kadai, tsugi no taio wo kanketsu ni tsutaeru koto desu.', topic: 'workplace' },
      { question: 'Shinkansen no shiteiseki to wa nan desu ka?', answer: 'Jizen ni zaseki bango ga kimerarete iru seki desu.', topic: 'travel' },
      { question: 'Sushi no shari to wa nan desu ka?', answer: 'Su de ajitsuke shita gohan no koto desu.', topic: 'food' },
    ],
  },
];

export default exampleDatasets;
